export const COMMAND_SUGGESTIONS = [
  'help',
  'list',
  'tps',
  'mspt',
  'save-all',
  'save-off',
  'save-on',
  'stop',
  'reload confirm',
  'whitelist list',
  'whitelist add',
  'whitelist remove',
  'op',
  'deop',
  'kick',
  'ban',
  'pardon',
  'gamemode survival',
  'gamemode creative',
  'gamemode adventure',
  'gamemode spectator',
  'difficulty peaceful',
  'difficulty easy',
  'difficulty normal',
  'difficulty hard',
  'time set day',
  'time set night',
  'weather clear',
  'weather rain',
  'gamerule keepInventory true',
  'gamerule keepInventory false',
  'tp',
  'give',
  'clear',
  'kill',
  'say',
  'title',
  'effect give',
  'effect clear',
  'enchant',
  'experience add',
  'paper entity',
]
